### ISSUE TITLE
Add: package ggtags

### ISSUE THREAD

**Issue by luismayta** [luismayta/emacs.d#156]
## The problem

Implement support for ggtags package emacs

## Environment

* Emacs version 24.5 higher

## Tasks

* [x] Make load packages ggtags
* [x] Make file for functions
* [x] Make info in rst
