### ISSUE TITLE
Support for package google translate

### ISSUE THREAD

**Issue by luismayta** [luismayta/emacs.d#157]
## The problem

Actually no having support for translate info english to spanish

## Environment

* Emacs version 24.5 higher:

## Details

Is necessary add info the package

## Tasks

* [x] Add: load package
* [x] Add: functions for package
* [x] Add: info project
